/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Lm1234AmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface Lm1234AmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface Lm1234AmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface Lm1234AmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLm1234AmbulanceWlEditorElement;
}
export interface Lm1234AmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLm1234AmbulanceWlListElement;
}
declare global {
    interface HTMLLm1234AmbulanceWlAppElement extends Components.Lm1234AmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLLm1234AmbulanceWlAppElement: {
        prototype: HTMLLm1234AmbulanceWlAppElement;
        new (): HTMLLm1234AmbulanceWlAppElement;
    };
    interface HTMLLm1234AmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLLm1234AmbulanceWlEditorElement extends Components.Lm1234AmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLm1234AmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLm1234AmbulanceWlEditorElement, ev: Lm1234AmbulanceWlEditorCustomEvent<HTMLLm1234AmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLm1234AmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLLm1234AmbulanceWlEditorElement, ev: Lm1234AmbulanceWlEditorCustomEvent<HTMLLm1234AmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLm1234AmbulanceWlEditorElement: {
        prototype: HTMLLm1234AmbulanceWlEditorElement;
        new (): HTMLLm1234AmbulanceWlEditorElement;
    };
    interface HTMLLm1234AmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLLm1234AmbulanceWlListElement extends Components.Lm1234AmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLm1234AmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLm1234AmbulanceWlListElement, ev: Lm1234AmbulanceWlListCustomEvent<HTMLLm1234AmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLm1234AmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLLm1234AmbulanceWlListElement, ev: Lm1234AmbulanceWlListCustomEvent<HTMLLm1234AmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLm1234AmbulanceWlListElement: {
        prototype: HTMLLm1234AmbulanceWlListElement;
        new (): HTMLLm1234AmbulanceWlListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lm1234-ambulance-wl-app": HTMLLm1234AmbulanceWlAppElement;
        "lm1234-ambulance-wl-editor": HTMLLm1234AmbulanceWlEditorElement;
        "lm1234-ambulance-wl-list": HTMLLm1234AmbulanceWlListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Lm1234AmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface Lm1234AmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: Lm1234AmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface Lm1234AmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: Lm1234AmbulanceWlListCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface Lm1234AmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface Lm1234AmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface Lm1234AmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "lm1234-ambulance-wl-app": Omit<Lm1234AmbulanceWlApp, keyof Lm1234AmbulanceWlAppAttributes> & { [K in keyof Lm1234AmbulanceWlApp & keyof Lm1234AmbulanceWlAppAttributes]?: Lm1234AmbulanceWlApp[K] } & { [K in keyof Lm1234AmbulanceWlApp & keyof Lm1234AmbulanceWlAppAttributes as `attr:${K}`]?: Lm1234AmbulanceWlAppAttributes[K] } & { [K in keyof Lm1234AmbulanceWlApp & keyof Lm1234AmbulanceWlAppAttributes as `prop:${K}`]?: Lm1234AmbulanceWlApp[K] };
        "lm1234-ambulance-wl-editor": Omit<Lm1234AmbulanceWlEditor, keyof Lm1234AmbulanceWlEditorAttributes> & { [K in keyof Lm1234AmbulanceWlEditor & keyof Lm1234AmbulanceWlEditorAttributes]?: Lm1234AmbulanceWlEditor[K] } & { [K in keyof Lm1234AmbulanceWlEditor & keyof Lm1234AmbulanceWlEditorAttributes as `attr:${K}`]?: Lm1234AmbulanceWlEditorAttributes[K] } & { [K in keyof Lm1234AmbulanceWlEditor & keyof Lm1234AmbulanceWlEditorAttributes as `prop:${K}`]?: Lm1234AmbulanceWlEditor[K] };
        "lm1234-ambulance-wl-list": Omit<Lm1234AmbulanceWlList, keyof Lm1234AmbulanceWlListAttributes> & { [K in keyof Lm1234AmbulanceWlList & keyof Lm1234AmbulanceWlListAttributes]?: Lm1234AmbulanceWlList[K] } & { [K in keyof Lm1234AmbulanceWlList & keyof Lm1234AmbulanceWlListAttributes as `attr:${K}`]?: Lm1234AmbulanceWlListAttributes[K] } & { [K in keyof Lm1234AmbulanceWlList & keyof Lm1234AmbulanceWlListAttributes as `prop:${K}`]?: Lm1234AmbulanceWlList[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lm1234-ambulance-wl-app": LocalJSX.IntrinsicElements["lm1234-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLLm1234AmbulanceWlAppElement>;
            "lm1234-ambulance-wl-editor": LocalJSX.IntrinsicElements["lm1234-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLLm1234AmbulanceWlEditorElement>;
            "lm1234-ambulance-wl-list": LocalJSX.IntrinsicElements["lm1234-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLLm1234AmbulanceWlListElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
